### ISSUE TITLE
[Bug]: Save button not working in Nuxt3 projects

### ISSUE THREAD

**Issue by DaanVervacke** [webdevnerdstuff/vuetify-inline-fields#47]
### Bug description

The save button is not working in Nuxt3. 
Nothing really happens, the fields stays open and there are no errors.

I've tested this on a VInlineTextField and VInlineTextArea component. 
I assume it's also an issue on the other components.

Please check out the Stackblitz project below.

### Steps to reproduce

1. Create a new Nuxt3 project
2. Add Vuetify and Vuetify Inline Fields as plugins
3. Add a Vuetify Inline Fields component
4. Try saving a new value

### Reproduction link

https://stackblitz.com/edit/github-jk7sle?file=app.vue

### Additional context

Enabling `defineModel` in `nuxt.config.ts` does not resolve the issue.

`vite: {
    vue: {
      script: {
        defineModel: true,
      },
    },
  },
`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
The fields are usually going to be doing some kind of updating of data (or at least assumed), so the save field is waiting for the "loading" to finish. In order to bypass this you just need to set the `loading-wait` prop to `false`. I was even stumped at this for a little bit! :)

https://stackblitz.com/edit/github-jk7sle-th6ny2?file=app.vue
